sim_metric: 'cosine' # choose form ['cosine', 'l2']
keep_hard: True # True for hard examples
Kmeans_with_cos_dist: True # True for using cosine similarity for kmeans clustering
emb_memory_loc: "embeddings\\image_embeddings.npy"
text_emb_memory_loc: None
paths_memory_loc: "embeddings\\image_paths.npy"
sorted_clusters_file_loc: "clustering\\results\\ncentroids_2000\\sorted_clusters"
save_folder: "clustering\\results\\ncentroids_2000"
path_str_dtype: "S24"
ncentroids: 2000 # 如果按39个为一族那么ncentroids应该为2564
dataset_size:  100000 
emb_size: 512
niter: 100
seed: 1234
